[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
slice-group-by = "0.3.0"
sscanf = "0.4.0"
strum = "0.24"
strum_macros = "0.24"
